### ISSUE TITLE
バーコードがほしい

### ISSUE THREAD

**Issue by mtgto** [nanaka-inside/kaisetsu-CoreUtils#1]
- 裏表紙にウソバーコードとウソISBNコードがほしい
- 表表紙の「Let's enjoy Coreutils life!」の文字が小さい
- 「はじめに」のページ番号が文字化けしている

**Comment by tboffice** [comment]
嘘バーコードは見本誌提出時に混乱のもとになるので避ける
ほかはもう古いしみなかったことにする
